---
title: "Looking through data"
author: "Taylor Blair"
date: "2/17/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

*Ha ha*

```{r}
# Load libraries
library(tidyverse)
library(reticulate)
library(readxl)
```


# Import and Wrangle Data

```{r}
## Import data 
reed_checkouts <- read_excel("data-raw/Hauser_Circulation_Statistics_2018-2020.xlsx")
## Rename variables
colnames(reed_checkouts) <- c("Title", "Author", "Published", "Location", "Barcode", "Call_No",
                              "Copies","Loaned", "Returned", "Patron")
### Create new variables
## Senior Thesis: A new boolean indicating checkout is a senior thesis
reed_checkouts$Thesis <- reed_checkouts$Call_No=="	Thesis"
## Remove unwanted columns
reed_checkouts <- subset(reed_checkouts, select = -c(Barcode, Call_No))
```
## Clean Columns

```{r}
## COLUMN: Publication date ##
## NOTE: Previously included copyright symbols, periods, and multiple dates
reed_checkouts$Published <- gsub("[^0-9]", "", reed_checkouts$Published)
reed_checkouts$Published <- substr(reed_checkouts$Published, 1, 4)

## COLUMN: Title ##
reed_checkouts$Title <- gsub('[/]{1}$', '', reed_checkouts$Title) #regex heckery

```

```{python}
import nltk
nltk.download('averaged_perceptron_tagger')
nltk.download('punkt')

import pandas as pd
def clean_str(s0):
  tagged = nltk.pos_tag(nltk.word_tokenize(s0))
  return " ".join([word[0] for word in tagged if word[1]=="NNP"])

def name_clean(authors):
  return [clean_str(mess) if mess == mess else "" for mess in authors]
  
#authors = name_clean(authors)

```

# Save and Export

```{r}
write_csv(reed_checkouts, "RCLC.csv")
```