---
title: "Stage Two"
author: "Ali Taqi"
date: "2/18/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# Import libraries
library(tidyverse)
# Source files
#source("clean.R")
reed_checkouts <- read_csv("RCLC.csv")
```

```{r}
# NOTES:
# See issues with problematic years < 1809 and tackle individually perhaps
reed_checkouts[which(reed_checkouts$Published < 1809),]
```

```{r}
# Suggestion: Use factors to remove unwanted locations or split the dataset
locations <- as.factor(reed_checkouts$Location)
levels(locations)
```

```{r}
patrons <- as.factor(reed_checkouts$Patron)
levels(patrons)
```

```{r}
classify_days <- function(dates){
  days <- c("Sun","Mon","Tue","Wed","Thu","Fri","Sat")
  my_class <- rep(NA, length(dates)) # Column classifying the day at a date
  for(i in 1:length(days)){
    idx <- grep(pattern = days[i], x = dates) # Matching indices from that classifier
    my_class[idx] <- days[i] 
  }
  my_class
}
```

```{r}
dates <- rfc2822(anytime(reed_checkouts[,]$Loaned))
date2 <- data.frame(dates) 
#date2
# if using dataframe, change length(dates) => ncol(dates) in classify_days
classify_days(dates)
```


