---
title: "Looking through data"
author: "Taylor Blair"
date: "2/17/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Load libraries
*Ha ha*

```{r}
library(tidyverse)

```


# Import Data
```{r}
reed_checkouts <- read_excel("data-raw/Item_Circulation_Statistics_2018-2020_PatronGroups.xlsx")

```


#Clean Columns

## Publication date

Previously included copyright symbols, periods, and multiple dates

```{r}
reed_checkouts$`Publication Date` <- gsub("[^0-9]", "", reed_checkouts$`Publication Date`)
reed_checkouts$`Publication Date` <- substr(reed_checkouts$`Publication Date`, 1, 4)
```

## Title


```{r}
reed_checkouts$Title <- gsub('[/]{1}$', '', reed_checkouts$Title) #regex heckery

```


# New Variables

## Senior Thesis

```{r}

reed_checkouts$Thesis <- reed_checkouts$`Call Number`=="	
Thesis"

```

# Remove variables

```{r}

reed_checkouts <- subset(reed_checkouts, select = -c(Barcode, `Call Number`))


```

# Variable names

```{r}

colnames(reed_checkouts) <- c("Title", "Author", "Published", "Location", "Copies",
                              "Loaned", "Returned", "Patron", "Thesis")

```


# Save
```{r}

write_csv(reed_checkouts, "RCLC.csv")

```